name: Compile LaTeX and Sync PDF

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document via latexmk
        uses: xu-cheng/latex-action@v3
        with:
          root_file: assets/translations/main.tex
          compiler: latexmk
          # Removed -g and -use-make to ignore missing bibliography files
          args: -pdf- -latexmkrc=none -jobname=strutt1933translation

      - name: Commit and Push Updated PDF
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Action Bot'
          author_email: 'actions@github.com'
          message: 'chore: auto-compiled latest PDF via latexmk'
          add: 'assets/translations/conical_shell.pdf'

